server.port: 8282
spring:
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/new-demo-realm/protocol/openid-connect/certs
#logging:
#  level:
#    root: INFO